import { ml_kem768 } from '@noble/post-quantum/ml-kem.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { base64ToBytes, bytesToBase64, utf8ToBytes } from './utils.js';

/**
 * Project VEIL — Post-Quantum Group Ratchets (MLS / TreeKEM)
 * 
 * Replaces pairwise O(N) message fan-out with TreeKEM O(log N) key encapsulation
 * and O(1) symmetric group message encryption using NIST FIPS 203 ML-KEM-768.
 */

// Helper to derive deterministic 64-byte seed for ML-KEM keygen
function deriveKeygenSeed(secret, label) {
  const info = utf8ToBytes(label);
  return hkdf(sha256, secret, new Uint8Array(32), info, 64);
}

// Helper to derive 32-byte step secret up the tree path
function deriveStepSecret(parentSecret, label) {
  const info = utf8ToBytes(label);
  return hkdf(sha256, parentSecret, new Uint8Array(32), info, 32);
}

/**
 * Calculates tree leaf capacity M as the next power of 2 (min 4, max 256)
 */
export function getTreeCapacity(memberCount) {
  let m = 4;
  while (m < memberCount && m < 256) {
    m *= 2;
  }
  return m;
}

/**
 * Computes direct path from a leaf node to the root (node 0)
 */
export function getNodeDirectPath(leafNodeIndex) {
  const path = [];
  let curr = leafNodeIndex;
  while (curr >= 0) {
    path.push(curr);
    if (curr === 0) break;
    curr = Math.floor((curr - 1) / 2);
  }
  return path;
}

/**
 * Computes the copath (sibling nodes) along the path from leaf to root
 */
export function getCopathNodes(leafNodeIndex) {
  const copath = [];
  let curr = leafNodeIndex;
  while (curr > 0) {
    const sib = (curr % 2 === 1) ? curr + 1 : curr - 1;
    const parent = Math.floor((curr - 1) / 2);
    copath.push({ copathNode: sib, parentNode: parent, childNode: curr });
    curr = parent;
  }
  return copath;
}

/**
 * Creates and initializes a new Post-Quantum TreeKEM group tree
 */
export function createGroupTree(groupId, members, myId) {
  const capacity = getTreeCapacity(members.length);
  const numNodes = 2 * capacity - 1;

  // Build roster with fixed leaf indices
  const roster = members.map((m, idx) => ({
    id: m.id,
    name: m.name || `Member-${m.id.slice(0, 4)}`,
    leafIndex: idx
  }));

  const myMember = roster.find(m => m.id === myId);
  const myLeafIndex = myMember ? myMember.leafIndex : 0;
  const myLeafNode = (capacity - 1) + myLeafIndex;

  // Initial group root seed generated by creator
  const initialRootSecret = new Uint8Array(32);
  crypto.getRandomValues(initialRootSecret);

  // Initialize public nodes array and creator's private secrets
  const publicNodes = Array.from({ length: numNodes }, () => null);
  const mySecrets = new Map(); // nodeIndex -> Uint8Array (sk)

  // Derive initial keypairs for all tree nodes from initialRootSecret
  for (let i = 0; i < numNodes; i++) {
    const seed = deriveKeygenSeed(initialRootSecret, `init_node_${groupId}_${i}`);
    const keys = ml_kem768.keygen(seed);
    publicNodes[i] = bytesToBase64(keys.publicKey);
  }

  // Populate creator's direct path secrets
  const myPath = getNodeDirectPath(myLeafNode);
  for (const nodeIdx of myPath) {
    const seed = deriveKeygenSeed(initialRootSecret, `init_node_${groupId}_${nodeIdx}`);
    const keys = ml_kem768.keygen(seed);
    mySecrets.set(nodeIdx, keys.secretKey);
  }

  const epoch = 1;
  const epochSecret = deriveStepSecret(initialRootSecret, `epoch_${groupId}_${epoch}`);
  const appSecret = deriveStepSecret(epochSecret, 'app_secret');

  const groupTree = {
    groupId,
    epoch,
    capacity,
    roster,
    myId,
    myLeafIndex,
    publicNodes, // array of base64 public keys
    mySecrets,   // Map of nodeIndex -> Uint8Array (private keys)
    epochSecret, // Uint8Array(32)
    appSecret,   // Uint8Array(32)
    messageCounters: new Map() // senderId -> seq
  };

  return {
    groupTree,
    initialCommit: {
      groupId,
      epoch: 1,
      capacity,
      roster,
      publicNodes,
      initialRootSecretB64: bytesToBase64(initialRootSecret)
    }
  };
}

/**
 * Initializes a non-creator member's TreeKEM tree from an initial commit
 */
export function initMemberFromInitialCommit(initialCommit, myId) {
  const { groupId, epoch, capacity, roster, publicNodes, initialRootSecretB64 } = initialCommit;
  const numNodes = 2 * capacity - 1;
  const initialRootSecret = base64ToBytes(initialRootSecretB64);

  const myMember = roster.find(m => m.id === myId);
  const myLeafIndex = myMember ? myMember.leafIndex : 0;
  const myLeafNode = (capacity - 1) + myLeafIndex;

  const mySecrets = new Map();
  const myPath = getNodeDirectPath(myLeafNode);

  // Non-creator derives secrets on their direct path from initialRootSecret
  for (const nodeIdx of myPath) {
    const seed = deriveKeygenSeed(initialRootSecret, `init_node_${groupId}_${nodeIdx}`);
    const keys = ml_kem768.keygen(seed);
    mySecrets.set(nodeIdx, keys.secretKey);
  }

  const epochSecret = deriveStepSecret(initialRootSecret, `epoch_${groupId}_${epoch}`);
  const appSecret = deriveStepSecret(epochSecret, 'app_secret');

  return {
    groupId,
    epoch,
    capacity,
    roster,
    myId,
    myLeafIndex,
    publicNodes: [...publicNodes],
    mySecrets,
    epochSecret,
    appSecret,
    messageCounters: new Map()
  };
}

/**
 * Creates a TreeKEM Commit:
 * Rotates committer's leaf secret, encapsulates new parent secrets to copath nodes,
 * and derives new epoch secret in O(log N).
 */
export function createTreeKemCommit(groupTree, committerId, { addedMembers = [], removedMemberIds = [] } = {}) {
  const { capacity, groupId, epoch } = groupTree;
  const newEpoch = epoch + 1;

  // Update roster if members added or removed
  let newRoster = [...groupTree.roster];
  if (removedMemberIds.length > 0) {
    const removeSet = new Set(removedMemberIds);
    newRoster = newRoster.filter(m => !removeSet.has(m.id));
  }
  if (addedMembers.length > 0) {
    const existingIds = new Set(newRoster.map(m => m.id));
    let nextAvailableLeaf = 0;
    while (newRoster.some(m => m.leafIndex === nextAvailableLeaf) && nextAvailableLeaf < capacity) {
      nextAvailableLeaf++;
    }
    for (const addM of addedMembers) {
      if (!existingIds.has(addM.id)) {
        newRoster.push({
          id: addM.id,
          name: addM.name || `Member-${addM.id.slice(0, 4)}`,
          leafIndex: nextAvailableLeaf++
        });
      }
    }
  }

  const myMember = newRoster.find(m => m.id === committerId);
  const myLeafIndex = myMember ? myMember.leafIndex : groupTree.myLeafIndex;
  const leafNode = (capacity - 1) + myLeafIndex;

  // Generate fresh random 32-byte leaf path secret
  const freshPathSecret = new Uint8Array(32);
  crypto.getRandomValues(freshPathSecret);

  let currSecret = freshPathSecret;
  let currNode = leafNode;

  // Update committer's leaf keypair
  const leafSeed = deriveKeygenSeed(currSecret, `node_keygen_${groupId}_${newEpoch}_${leafNode}`);
  const leafKeys = ml_kem768.keygen(leafSeed);

  const updatedPublicNodes = [...groupTree.publicNodes];
  updatedPublicNodes[leafNode] = bytesToBase64(leafKeys.publicKey);

  const newMySecrets = new Map(groupTree.mySecrets);
  newMySecrets.set(leafNode, leafKeys.secretKey);

  const copathEncryptions = [];
  const updatedNodesList = [{ nodeIndex: leafNode, publicKeyB64: updatedPublicNodes[leafNode] }];

  // Walk up direct path to root, encapsulating to copath siblings in O(log N)
  while (currNode > 0) {
    const sib = (currNode % 2 === 1) ? currNode + 1 : currNode - 1;
    const parent = Math.floor((currNode - 1) / 2);

    // Derive next secret for parent
    const nextSecret = deriveStepSecret(currSecret, `step_${groupId}_${newEpoch}_${parent}`);

    // Encapsulate nextSecret to sibling's public key if available
    const sibPkB64 = updatedPublicNodes[sib];
    if (sibPkB64) {
      const sibPk = base64ToBytes(sibPkB64);
      const { cipherText, sharedSecret } = ml_kem768.encapsulate(sibPk);

      // Mask nextSecret with sharedSecret
      const wrapped = new Uint8Array(32);
      for (let j = 0; j < 32; j++) {
        wrapped[j] = nextSecret[j] ^ sharedSecret[j];
      }

      copathEncryptions.push({
        copathNode: sib,
        parentNode: parent,
        kemCiphertextB64: bytesToBase64(cipherText),
        wrappedSecretB64: bytesToBase64(wrapped)
      });
    }

    // Derive new keypair for parent node
    const pSeed = deriveKeygenSeed(nextSecret, `node_keygen_${groupId}_${newEpoch}_${parent}`);
    const pKeys = ml_kem768.keygen(pSeed);

    updatedPublicNodes[parent] = bytesToBase64(pKeys.publicKey);
    newMySecrets.set(parent, pKeys.secretKey);
    updatedNodesList.push({ nodeIndex: parent, publicKeyB64: updatedPublicNodes[parent] });

    currSecret = nextSecret;
    currNode = parent;
  }

  // Root secret is currSecret at node 0
  const newEpochSecret = deriveStepSecret(currSecret, `epoch_${groupId}_${newEpoch}`);
  const newAppSecret = deriveStepSecret(newEpochSecret, 'app_secret');

  const newGroupTree = {
    ...groupTree,
    epoch: newEpoch,
    roster: newRoster,
    publicNodes: updatedPublicNodes,
    mySecrets: newMySecrets,
    epochSecret: newEpochSecret,
    appSecret: newAppSecret,
    messageCounters: new Map()
  };

  const commitPayload = {
    type: 'tree_kem_commit',
    groupId,
    epoch: newEpoch,
    committerId,
    copathEncryptions,
    updatedNodes: updatedNodesList,
    roster: newRoster
  };

  return { newGroupTree, commitPayload };
}

/**
 * Processes an incoming TreeKEM Commit from another member:
 * Decapsulates the relevant copath ciphertext using local node secret,
 * hashes up to root, and advances epoch in O(log N).
 */
export function processTreeKemCommit(groupTree, myId, commitPayload) {
  const { capacity, groupId } = groupTree;
  const { epoch, committerId, copathEncryptions, updatedNodes, roster } = commitPayload;

  if (committerId === myId) {
    return groupTree; // Already applied locally by committer
  }

  // Update public nodes with committer's changes
  const updatedPublicNodes = [...groupTree.publicNodes];
  for (const node of updatedNodes) {
    updatedPublicNodes[node.nodeIndex] = node.publicKeyB64;
  }

  const myMember = (roster || groupTree.roster).find(m => m.id === myId);
  if (!myMember) {
    throw new Error(`Member ${myId} is not in group roster for epoch ${epoch}`);
  }

  const myLeafNode = (capacity - 1) + myMember.leafIndex;
  const myPath = getNodeDirectPath(myLeafNode);
  const myPathSet = new Set(myPath);

  // Find the single copath encryption matching our direct path
  const match = copathEncryptions.find(c => myPathSet.has(c.copathNode));
  if (!match) {
    throw new Error(`No copath intersection found for member ${myId} in epoch ${epoch} commit`);
  }

  const copathSk = groupTree.mySecrets.get(match.copathNode);
  if (!copathSk) {
    throw new Error(`Missing local secret key for copath node ${match.copathNode}`);
  }

  // Decapsulate sharedSecret using local copath secret key
  const kemCt = base64ToBytes(match.kemCiphertextB64);
  const sharedSecret = ml_kem768.decapsulate(kemCt, copathSk);

  // Unmask parent secret
  const wrapped = base64ToBytes(match.wrappedSecretB64);
  const recoveredParentSecret = new Uint8Array(32);
  for (let j = 0; j < 32; j++) {
    recoveredParentSecret[j] = wrapped[j] ^ sharedSecret[j];
  }

  const newMySecrets = new Map(groupTree.mySecrets);

  // Re-derive keys up the direct path starting from match.parentNode
  let currSecret = recoveredParentSecret;
  let currNode = match.parentNode;

  const pSeed = deriveKeygenSeed(currSecret, `node_keygen_${groupId}_${epoch}_${currNode}`);
  const pKeys = ml_kem768.keygen(pSeed);
  newMySecrets.set(currNode, pKeys.secretKey);

  while (currNode > 0) {
    const parent = Math.floor((currNode - 1) / 2);
    currSecret = deriveStepSecret(currSecret, `step_${groupId}_${epoch}_${parent}`);
    currNode = parent;

    const parentSeed = deriveKeygenSeed(currSecret, `node_keygen_${groupId}_${epoch}_${currNode}`);
    const parentKeys = ml_kem768.keygen(parentSeed);
    newMySecrets.set(currNode, parentKeys.secretKey);
  }

  // Derive identical epoch secret and application secret
  const newEpochSecret = deriveStepSecret(currSecret, `epoch_${groupId}_${epoch}`);
  const newAppSecret = deriveStepSecret(newEpochSecret, 'app_secret');

  return {
    ...groupTree,
    epoch,
    roster: roster || groupTree.roster,
    publicNodes: updatedPublicNodes,
    mySecrets: newMySecrets,
    epochSecret: newEpochSecret,
    appSecret: newAppSecret,
    messageCounters: new Map()
  };
}

/**
 * Encrypts an application message for the entire group using O(1) symmetric TreeKEM group key
 */
export async function encryptGroupMlsMessage(groupTree, myId, payload) {
  const { groupId, epoch, appSecret, roster } = groupTree;
  
  // Advance sender sequence counter
  const currSeq = (groupTree.messageCounters.get(myId) || 0) + 1;
  groupTree.messageCounters.set(myId, currSeq);

  // Derive message key from appSecret, senderId, and sequence
  const info = utf8ToBytes(`VEIL-MLS-MSG-${myId}-${currSeq}`);
  const msgKeyBytes = hkdf(sha256, appSecret, new Uint8Array(32), info, 32);

  const aesKey = await crypto.subtle.importKey(
    'raw',
    msgKeyBytes,
    { name: 'AES-GCM' },
    false,
    ['encrypt']
  );

  const iv = new Uint8Array(12);
  crypto.getRandomValues(iv);

  const aad = utf8ToBytes(JSON.stringify({
    groupId,
    epoch,
    senderId: myId,
    seq: currSeq
  }));

  const plaintextBytes = utf8ToBytes(JSON.stringify(payload));
  const ciphertextBuf = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv, additionalData: aad },
    aesKey,
    plaintextBytes
  );

  const recipients = (roster || []).map(m => m.id).filter(id => id !== myId);

  return {
    type: 'group_mls_msg',
    groupId,
    epoch,
    senderId: myId,
    seq: currSeq,
    ivB64: bytesToBase64(iv),
    ciphertextB64: bytesToBase64(new Uint8Array(ciphertextBuf)),
    recipients
  };
}

/**
 * Decrypts a group message in O(1) using the group's current epoch appSecret
 */
export async function decryptGroupMlsMessage(groupTree, mlsEnvelope) {
  const { groupId, epoch, senderId, seq, ivB64, ciphertextB64 } = mlsEnvelope;

  if (groupId !== groupTree.groupId) {
    throw new Error(`Message groupId (${groupId}) does not match tree groupId (${groupTree.groupId})`);
  }

  if (epoch !== groupTree.epoch) {
    throw new Error(`Message epoch (${epoch}) does not match local tree epoch (${groupTree.epoch})`);
  }

  // Derive identical message key
  const info = utf8ToBytes(`VEIL-MLS-MSG-${senderId}-${seq}`);
  const msgKeyBytes = hkdf(sha256, groupTree.appSecret, new Uint8Array(32), info, 32);

  const aesKey = await crypto.subtle.importKey(
    'raw',
    msgKeyBytes,
    { name: 'AES-GCM' },
    false,
    ['decrypt']
  );

  const iv = base64ToBytes(ivB64);
  const ciphertext = base64ToBytes(ciphertextB64);

  const aad = utf8ToBytes(JSON.stringify({
    groupId,
    epoch,
    senderId,
    seq
  }));

  const decryptedBuf = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv, additionalData: aad },
    aesKey,
    ciphertext
  );

  const decryptedStr = new TextDecoder().decode(decryptedBuf);
  return JSON.parse(decryptedStr);
}

/**
 * Serializes GroupTree for secure IndexedDB persistence
 */
export function serializeGroupTree(groupTree) {
  const secretsObj = {};
  for (const [nodeIdx, sk] of groupTree.mySecrets.entries()) {
    secretsObj[nodeIdx] = bytesToBase64(sk);
  }

  return JSON.stringify({
    groupId: groupTree.groupId,
    epoch: groupTree.epoch,
    capacity: groupTree.capacity,
    roster: groupTree.roster,
    myId: groupTree.myId,
    myLeafIndex: groupTree.myLeafIndex,
    publicNodes: groupTree.publicNodes,
    mySecretsB64: secretsObj,
    epochSecretB64: bytesToBase64(groupTree.epochSecret),
    appSecretB64: bytesToBase64(groupTree.appSecret)
  });
}

/**
 * Deserializes GroupTree from stored JSON
 */
export function deserializeGroupTree(jsonStr) {
  const obj = JSON.parse(jsonStr);
  const mySecrets = new Map();
  for (const [nodeIdx, skB64] of Object.entries(obj.mySecretsB64 || {})) {
    mySecrets.set(Number(nodeIdx), base64ToBytes(skB64));
  }

  return {
    groupId: obj.groupId,
    epoch: obj.epoch,
    capacity: obj.capacity,
    roster: obj.roster,
    myId: obj.myId,
    myLeafIndex: obj.myLeafIndex,
    publicNodes: obj.publicNodes,
    mySecrets,
    epochSecret: base64ToBytes(obj.epochSecretB64),
    appSecret: base64ToBytes(obj.appSecretB64),
    messageCounters: new Map()
  };
}
