// WhatsApp-style categorized emoji database with keyword search tags

export const EMOJI_CATEGORIES = [
  { id: 'recent', name: 'Recent', icon: '🕒' },
  { id: 'smileys', name: 'Smileys & Emotion', icon: '😀' },
  { id: 'people', name: 'People & Body', icon: '🧑' },
  { id: 'animals', name: 'Animals & Nature', icon: '🐶' },
  { id: 'food', name: 'Food & Drink', icon: '🍕' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'travel', name: 'Travel & Places', icon: '🚗' },
  { id: 'objects', name: 'Objects', icon: '💡' },
  { id: 'symbols', name: 'Symbols', icon: '🔣' },
  { id: 'flags', name: 'Flags', icon: '🚩' }
];

export const EMOJI_DATABASE = {
  smileys: [
    { emoji: '😀', tags: ['grinning', 'happy', 'smile', 'joy'] },
    { emoji: '😃', tags: ['smiling', 'happy', 'joy', 'smile'] },
    { emoji: '😄', tags: ['smile', 'joy', 'happy', 'laugh'] },
    { emoji: '😁', tags: ['beaming', 'teeth', 'smile', 'happy'] },
    { emoji: '😆', tags: ['laughing', 'lol', 'happy', 'closed eyes'] },
    { emoji: '😅', tags: ['sweat', 'nervous', 'relief', 'smile'] },
    { emoji: '🤣', tags: ['rofl', 'rolling', 'laughing', 'crying', 'floor'] },
    { emoji: '😂', tags: ['joy', 'tears', 'crying', 'lol', 'laugh'] },
    { emoji: '🙂', tags: ['slightly smiling', 'smile', 'mild'] },
    { emoji: '🙃', tags: ['upside down', 'silly', 'sarcasm'] },
    { emoji: '😉', tags: ['wink', 'flirt', 'joke'] },
    { emoji: '😊', tags: ['blush', 'warm', 'happy', 'smile'] },
    { emoji: '😇', tags: ['halo', 'angel', 'innocent'] },
    { emoji: '🥰', tags: ['hearts', 'love', 'adore', 'crush'] },
    { emoji: '😍', tags: ['heart eyes', 'love', 'in love'] },
    { emoji: '🤩', tags: ['star struck', 'excited', 'wow'] },
    { emoji: '😘', tags: ['kiss', 'blow kiss', 'love'] },
    { emoji: '😗', tags: ['kissing', 'whistle'] },
    { emoji: '😚', tags: ['kiss', 'blush', 'eyes closed'] },
    { emoji: '😙', tags: ['kiss', 'smiling'] },
    { emoji: '😋', tags: ['yummy', 'tasty', 'delicious', 'tongue'] },
    { emoji: '😛', tags: ['tongue', 'playful'] },
    { emoji: '😜', tags: ['wink tongue', 'crazy', 'joke'] },
    { emoji: '🤪', tags: ['zany', 'wild', 'crazy', 'goofy'] },
    { emoji: '😝', tags: ['squint tongue', 'playful'] },
    { emoji: '🤑', tags: ['money', 'rich', 'dollar', 'cash'] },
    { emoji: '🤗', tags: ['hugs', 'open hands', 'friendly'] },
    { emoji: '🤭', tags: ['hand over mouth', 'giggle', 'oops'] },
    { emoji: '🤫', tags: ['shh', 'quiet', 'secret', 'stealth'] },
    { emoji: '🤔', tags: ['thinking', 'ponder', 'hmm', 'curious'] },
    { emoji: '🤐', tags: ['zipper', 'silent', 'confidential', 'secret'] },
    { emoji: '🤨', tags: ['raised eyebrow', 'skeptical', 'suspicious'] },
    { emoji: '😐', tags: ['neutral', 'meh', 'blank'] },
    { emoji: '😑', tags: ['expressionless', 'unimpressed'] },
    { emoji: '😶', tags: ['no mouth', 'speechless', 'silent'] },
    { emoji: '😏', tags: ['smirk', 'smug', 'flirt'] },
    { emoji: '😒', tags: ['unamused', 'bored', 'annoyed'] },
    { emoji: '🙄', tags: ['eye roll', 'whatever', 'annoyed'] },
    { emoji: '😬', tags: ['grimace', 'awkward', 'cringe'] },
    { emoji: '🤥', tags: ['lying', 'pinocchio', 'fake'] },
    { emoji: '😌', tags: ['relieved', 'peaceful', 'calm'] },
    { emoji: '😔', tags: ['pensive', 'sad', 'down'] },
    { emoji: '😪', tags: ['sleepy', 'tired', 'bubble'] },
    { emoji: '🤤', tags: ['drooling', 'crave', 'hungry'] },
    { emoji: '😴', tags: ['sleeping', 'zzz', 'night'] },
    { emoji: '😷', tags: ['mask', 'sick', 'virus', 'quarantine'] },
    { emoji: '🤒', tags: ['thermometer', 'fever', 'ill'] },
    { emoji: '🤕', tags: ['bandage', 'hurt', 'injury'] },
    { emoji: '🤢', tags: ['nauseated', 'disgust', 'gross'] },
    { emoji: '🤮', tags: ['vomit', 'barf', 'gross'] },
    { emoji: '🤧', tags: ['sneezing', 'allergy', 'cold'] },
    { emoji: '🥵', tags: ['hot', 'overheated', 'heat'] },
    { emoji: '🥶', tags: ['cold', 'freezing', 'ice', 'frozen'] },
    { emoji: '🥴', tags: ['woozy', 'drunk', 'dizzy'] },
    { emoji: '😵', tags: ['dizzy', 'faint', 'dead'] },
    { emoji: '🤯', tags: ['exploding head', 'mind blown', 'shock'] },
    { emoji: '🤠', tags: ['cowboy', 'hat', 'wild west'] },
    { emoji: '🥳', tags: ['partying', 'celebrate', 'birthday'] },
    { emoji: '😎', tags: ['sunglasses', 'cool', 'cyber', 'hacker'] },
    { emoji: '🤓', tags: ['nerd', 'geek', 'glasses', 'coder'] },
    { emoji: '🧐', tags: ['monocle', 'inspect', 'investigate'] },
    { emoji: '😕', tags: ['confused', 'unsure'] },
    { emoji: '😟', tags: ['worried', 'nervous'] },
    { emoji: '🙁', tags: ['frowning', 'sad'] },
    { emoji: '😮', tags: ['open mouth', 'surprised', 'gasp'] },
    { emoji: '😯', tags: ['hushed', 'stunned'] },
    { emoji: '😲', tags: ['astonished', 'shocked'] },
    { emoji: '😳', tags: ['flushed', 'embarrassed', 'wide eyes'] },
    { emoji: '🥺', tags: ['pleading', 'puppy eyes', 'beg'] },
    { emoji: '😦', tags: ['frowning open mouth', 'shock'] },
    { emoji: '😧', tags: ['anguished', 'scared'] },
    { emoji: '😨', tags: ['fearful', 'panicked', 'scared'] },
    { emoji: '😰', tags: ['anxious', 'blue', 'sweat'] },
    { emoji: '😥', tags: ['sad but relieved', 'phew'] },
    { emoji: '😢', tags: ['crying', 'tear', 'sad'] },
    { emoji: '😭', tags: ['loudly crying', 'bawling', 'devastated'] },
    { emoji: '😱', tags: ['screaming', 'fear', 'horror', 'shock'] },
    { emoji: '😖', tags: ['confounded', 'quiver'] },
    { emoji: '😣', tags: ['persevering', 'struggle'] },
    { emoji: '😞', tags: ['disappointed', 'hopeless'] },
    { emoji: '😓', tags: ['downcast sweat', 'hard work'] },
    { emoji: '😩', tags: ['weary', 'tired', 'frustrated'] },
    { emoji: '😫', tags: ['tired', 'exhausted'] },
    { emoji: '🥱', tags: ['yawning', 'bored', 'tired'] },
    { emoji: '😤', tags: ['triumph', 'steam', 'frustrated'] },
    { emoji: '😡', tags: ['pouting', 'angry', 'mad', 'red'] },
    { emoji: '😠', tags: ['angry', 'annoyed', 'grumpy'] },
    { emoji: '🤬', tags: ['cursing', 'censored', 'furious'] },
    { emoji: '😈', tags: ['devil smile', 'evil', 'naughty'] },
    { emoji: '👿', tags: ['angry devil', 'demon'] },
    { emoji: '💀', tags: ['skull', 'dead', 'danger', 'hacker'] },
    { emoji: '☠️', tags: ['crossbones', 'pirate', 'toxic', 'danger'] },
    { emoji: '💩', tags: ['poop', 'crap', 'funny'] },
    { emoji: '🤡', tags: ['clown', 'fool', 'joke'] },
    { emoji: '👻', tags: ['ghost', 'spooky', 'phantom', 'stealth'] },
    { emoji: '👽', tags: ['alien', 'ufo', 'extraterrestrial'] },
    { emoji: '👾', tags: ['alien monster', 'retro', 'game', 'arcade'] },
    { emoji: '🤖', tags: ['robot', 'bot', 'ai', 'cyber', 'tech'] },
    { emoji: '😺', tags: ['cat smile', 'kitty'] },
    { emoji: '😸', tags: ['cat grin'] },
    { emoji: '😹', tags: ['cat joy tears'] },
    { emoji: '😻', tags: ['cat heart eyes'] },
    { emoji: '😼', tags: ['cat smirk'] },
    { emoji: '😽', tags: ['cat kiss'] },
    { emoji: '🙀', tags: ['cat scream'] },
    { emoji: '😿', tags: ['cat crying'] },
    { emoji: '😾', tags: ['cat pouting'] }
  ],
  people: [
    { emoji: '👋', tags: ['wave', 'hello', 'bye', 'hi'] },
    { emoji: '🤚', tags: ['raised back of hand'] },
    { emoji: '🖐️', tags: ['fingers splayed'] },
    { emoji: '✋', tags: ['raised hand', 'stop', 'high five'] },
    { emoji: '🖖', tags: ['vulcan', 'spock', 'live long'] },
    { emoji: '👌', tags: ['ok', 'perfect', 'fine'] },
    { emoji: '🤌', tags: ['pinched fingers', 'italian', 'what'] },
    { emoji: '🤏', tags: ['pinching', 'small', 'tiny'] },
    { emoji: '✌️', tags: ['victory', 'peace', 'two'] },
    { emoji: '🤞', tags: ['crossed fingers', 'luck', 'hope'] },
    { emoji: '🤟', tags: ['love you', 'sign'] },
    { emoji: '🤘', tags: ['rock on', 'horns', 'metal'] },
    { emoji: '🤙', tags: ['call me', 'hang loose', 'shaka'] },
    { emoji: '👈', tags: ['point left'] },
    { emoji: '👉', tags: ['point right'] },
    { emoji: '👆', tags: ['point up'] },
    { emoji: '🖕', tags: ['middle finger'] },
    { emoji: '👇', tags: ['point down'] },
    { emoji: '☝️', tags: ['index up', 'one'] },
    { emoji: '👍', tags: ['thumbs up', 'like', 'approve', 'yes'] },
    { emoji: '👎', tags: ['thumbs down', 'dislike', 'no'] },
    { emoji: '✊', tags: ['fist', 'power', 'solidarity'] },
    { emoji: '👊', tags: ['punch', 'fist bump', 'bro'] },
    { emoji: '🤛', tags: ['left fist'] },
    { emoji: '🤜', tags: ['right fist'] },
    { emoji: '👏', tags: ['clap', 'applause', 'bravo'] },
    { emoji: '🙌', tags: ['raising hands', 'celebrate', 'praise'] },
    { emoji: '👐', tags: ['open hands'] },
    { emoji: '🤲', tags: ['palms up', 'prayer'] },
    { emoji: '🤝', tags: ['handshake', 'deal', 'agreement'] },
    { emoji: '🙏', tags: ['praying', 'please', 'thank you', 'namaste'] },
    { emoji: '✍️', tags: ['writing', 'author'] },
    { emoji: '💅', tags: ['nail polish', 'slay', 'sassy'] },
    { emoji: '🤳', tags: ['selfie', 'camera'] },
    { emoji: '💪', tags: ['muscle', 'strong', 'flex', 'bicep'] },
    { emoji: '🧠', tags: ['brain', 'mind', 'genius', 'smart'] },
    { emoji: '👀', tags: ['eyes', 'look', 'see', 'watch'] },
    { emoji: '👁️', tags: ['eye', 'vision', 'monitor'] },
    { emoji: '🕵️', tags: ['detective', 'agent', 'spy', 'sleuth', 'secret'] },
    { emoji: '🧑‍💻', tags: ['coder', 'hacker', 'programmer', 'tech'] },
    { emoji: '🦸', tags: ['superhero', 'hero'] },
    { emoji: '🥷', tags: ['ninja', 'stealth', 'shadow', 'covert'] }
  ],
  animals: [
    { emoji: '🐶', tags: ['dog', 'puppy', 'pet'] },
    { emoji: '🐱', tags: ['cat', 'kitten'] },
    { emoji: '🐭', tags: ['mouse'] },
    { emoji: '🐹', tags: ['hamster'] },
    { emoji: '🐰', tags: ['rabbit', 'bunny'] },
    { emoji: '🦊', tags: ['fox'] },
    { emoji: '🐻', tags: ['bear'] },
    { emoji: '🐼', tags: ['panda'] },
    { emoji: '🐨', tags: ['koala'] },
    { emoji: '🐯', tags: ['tiger'] },
    { emoji: '🦁', tags: ['lion', 'king'] },
    { emoji: '🐮', tags: ['cow'] },
    { emoji: '🐷', tags: ['pig'] },
    { emoji: '🐸', tags: ['frog'] },
    { emoji: '🐵', tags: ['monkey'] },
    { emoji: '🐔', tags: ['chicken'] },
    { emoji: '🐧', tags: ['penguin'] },
    { emoji: '🦅', tags: ['eagle', 'bird'] },
    { emoji: '🦉', tags: ['owl', 'wise'] },
    { emoji: '🦇', tags: ['bat', 'vampire'] },
    { emoji: '🐺', tags: ['wolf', 'pack'] },
    { emoji: '🐗', tags: ['boar'] },
    { emoji: '🦄', tags: ['unicorn', 'magic'] },
    { emoji: '🐝', tags: ['bee', 'honey'] },
    { emoji: '🐛', tags: ['bug', 'glitch'] },
    { emoji: '🦋', tags: ['butterfly'] },
    { emoji: '🐌', tags: ['snail', 'slow'] },
    { emoji: '🐞', tags: ['ladybug'] },
    { emoji: '🐜', tags: ['ant'] },
    { emoji: '🕷️', tags: ['spider', 'web', 'cyber'] },
    { emoji: '🦂', tags: ['scorpion'] },
    { emoji: '🐢', tags: ['turtle'] },
    { emoji: '🐍', tags: ['snake', 'python'] },
    { emoji: '🦎', tags: ['lizard'] },
    { emoji: '🦖', tags: ['t-rex', 'dinosaur'] },
    { emoji: '🐙', tags: ['octopus'] },
    { emoji: '🦑', tags: ['squid'] },
    { emoji: '🦐', tags: ['shrimp'] },
    { emoji: '🦞', tags: ['lobster'] },
    { emoji: '🦀', tags: ['crab'] },
    { emoji: '🐡', tags: ['blowfish'] },
    { emoji: '🐠', tags: ['tropical fish'] },
    { emoji: '🐟', tags: ['fish'] },
    { emoji: '🐬', tags: ['dolphin'] },
    { emoji: '🐳', tags: ['whale'] },
    { emoji: '🦈', tags: ['shark'] },
    { emoji: '🐊', tags: ['crocodile'] },
    { emoji: '🐆', tags: ['leopard'] },
    { emoji: '🦓', tags: ['zebra'] },
    { emoji: '🦍', tags: ['gorilla', 'ape'] },
    { emoji: '🦧', tags: ['orangutan'] },
    { emoji: '🐘', tags: ['elephant'] },
    { emoji: '🦛', tags: ['hippo'] },
    { emoji: '🦏', tags: ['rhino'] },
    { emoji: '🐪', tags: ['camel'] },
    { emoji: '🦒', tags: ['giraffe'] },
    { emoji: '🦘', tags: ['kangaroo'] },
    { emoji: '🌱', tags: ['seedling', 'plant'] },
    { emoji: '🌲', tags: ['tree', 'forest'] },
    { emoji: '🌴', tags: ['palm tree'] },
    { emoji: '🌵', tags: ['cactus'] },
    { emoji: '🌸', tags: ['cherry blossom', 'flower'] },
    { emoji: '🌹', tags: ['rose', 'love'] },
    { emoji: '🌻', tags: ['sunflower'] },
    { emoji: '🍀', tags: ['four leaf clover', 'luck'] }
  ],
  food: [
    { emoji: '🍏', tags: ['green apple'] },
    { emoji: '🍎', tags: ['red apple'] },
    { emoji: '🍐', tags: ['pear'] },
    { emoji: '🍊', tags: ['orange', 'citrus'] },
    { emoji: '🍋', tags: ['lemon', 'sour'] },
    { emoji: '🍌', tags: ['banana'] },
    { emoji: '🍉', tags: ['watermelon'] },
    { emoji: '🍇', tags: ['grapes'] },
    { emoji: '🍓', tags: ['strawberry'] },
    { emoji: '🫐', tags: ['blueberries'] },
    { emoji: '🍈', tags: ['melon'] },
    { emoji: '🍒', tags: ['cherries'] },
    { emoji: '🍑', tags: ['peach'] },
    { emoji: '🍍', tags: ['pineapple'] },
    { emoji: '🥭', tags: ['mango'] },
    { emoji: '🥥', tags: ['coconut'] },
    { emoji: '🥝', tags: ['kiwi'] },
    { emoji: '🍅', tags: ['tomato'] },
    { emoji: '🥑', tags: ['avocado'] },
    { emoji: '🥦', tags: ['broccoli'] },
    { emoji: '🌽', tags: ['corn'] },
    { emoji: '🌶️', tags: ['hot pepper', 'spicy'] },
    { emoji: '🍄', tags: ['mushroom'] },
    { emoji: '🥜', tags: ['peanuts'] },
    { emoji: '🍞', tags: ['bread'] },
    { emoji: '🥐', tags: ['croissant'] },
    { emoji: '🥖', tags: ['baguette'] },
    { emoji: '🥨', tags: ['pretzel'] },
    { emoji: '🥯', tags: ['bagel'] },
    { emoji: '🥞', tags: ['pancakes'] },
    { emoji: '🧇', tags: ['waffle'] },
    { emoji: '🧀', tags: ['cheese'] },
    { emoji: '🍖', tags: ['meat on bone'] },
    { emoji: '🍗', tags: ['chicken leg'] },
    { emoji: '🥩', tags: ['steak'] },
    { emoji: '🥓', tags: ['bacon'] },
    { emoji: '🍔', tags: ['burger', 'hamburger', 'fast food'] },
    { emoji: '🍟', tags: ['fries', 'french fries'] },
    { emoji: '🍕', tags: ['pizza', 'slice'] },
    { emoji: '🌭', tags: ['hotdog'] },
    { emoji: '🥪', tags: ['sandwich'] },
    { emoji: '🌮', tags: ['taco', 'mexican'] },
    { emoji: '🌯', tags: ['burrito'] },
    { emoji: '🫔', tags: ['tamale'] },
    { emoji: '🥗', tags: ['salad', 'healthy'] },
    { emoji: '🍝', tags: ['spaghetti', 'pasta'] },
    { emoji: '🍜', tags: ['ramen', 'noodles'] },
    { emoji: '🍲', tags: ['stew', 'pot'] },
    { emoji: '🍣', tags: ['sushi', 'japanese'] },
    { emoji: '🍱', tags: ['bento box'] },
    { emoji: '🥟', tags: ['dumpling'] },
    { emoji: '🍤', tags: ['fried shrimp'] },
    { emoji: '🍙', tags: ['rice ball'] },
    { emoji: '🍚', tags: ['cooked rice'] },
    { emoji: '🍦', tags: ['ice cream', 'soft'] },
    { emoji: '🍧', tags: ['shaved ice'] },
    { emoji: '🍨', tags: ['ice cream bowl'] },
    { emoji: '🍩', tags: ['donut'] },
    { emoji: '🍪', tags: ['cookie', 'biscuit'] },
    { emoji: '🎂', tags: ['birthday cake'] },
    { emoji: '🍰', tags: ['cake slice'] },
    { emoji: '🧁', tags: ['cupcake'] },
    { emoji: '🥧', tags: ['pie'] },
    { emoji: '🍫', tags: ['chocolate'] },
    { emoji: '🍬', tags: ['candy'] },
    { emoji: '🍭', tags: ['lollipop'] },
    { emoji: '☕', tags: ['coffee', 'tea', 'cafe'] },
    { emoji: '🍵', tags: ['green tea', 'matcha'] },
    { emoji: '🧃', tags: ['juice box'] },
    { emoji: '🥤', tags: ['soda', 'cup with straw'] },
    { emoji: '🧋', tags: ['boba', 'bubble tea'] },
    { emoji: '🍺', tags: ['beer', 'cheers'] },
    { emoji: '🍻', tags: ['clinking beer mugs'] },
    { emoji: '🍷', tags: ['wine'] },
    { emoji: '🍸', tags: ['cocktail', 'martini'] },
    { emoji: '🍹', tags: ['tropical drink'] },
    { emoji: '🍾', tags: ['champagne', 'celebrate'] }
  ],
  activities: [
    { emoji: '⚽', tags: ['soccer', 'football'] },
    { emoji: '🏀', tags: ['basketball'] },
    { emoji: '🏈', tags: ['american football'] },
    { emoji: '⚾', tags: ['baseball'] },
    { emoji: '🥎', tags: ['softball'] },
    { emoji: '🎾', tags: ['tennis'] },
    { emoji: '🏐', tags: ['volleyball'] },
    { emoji: '🏉', tags: ['rugby'] },
    { emoji: '🥏', tags: ['frisbee'] },
    { emoji: '🎱', tags: ['pool', '8 ball', 'billiards'] },
    { emoji: '🏓', tags: ['ping pong', 'table tennis'] },
    { emoji: '🏸', tags: ['badminton'] },
    { emoji: '🏒', tags: ['ice hockey'] },
    { emoji: '🥊', tags: ['boxing glove'] },
    { emoji: '🥋', tags: ['martial arts', 'karate'] },
    { emoji: '🎯', tags: ['target', 'bullseye', 'goal'] },
    { emoji: '⛳', tags: ['golf'] },
    { emoji: '⛸️', tags: ['ice skate'] },
    { emoji: '🎣', tags: ['fishing'] },
    { emoji: '🤿', tags: ['diving mask', 'snorkel'] },
    { emoji: '🎽', tags: ['running shirt'] },
    { emoji: '🎿', tags: ['skis'] },
    { emoji: '🛷', tags: ['sled'] },
    { emoji: '🥌', tags: ['curling'] },
    { emoji: '🛹', tags: ['skateboard'] },
    { emoji: '🛼', tags: ['roller skate'] },
    { emoji: '🎮', tags: ['video game', 'controller', 'gaming'] },
    { emoji: '🕹️', tags: ['joystick', 'arcade', 'retro'] },
    { emoji: '🎰', tags: ['slot machine', 'casino'] },
    { emoji: '🎲', tags: ['dice', 'game', 'random'] },
    { emoji: '🧩', tags: ['puzzle', 'piece'] },
    { emoji: '🎨', tags: ['art', 'palette', 'paint'] },
    { emoji: '🎭', tags: ['theater', 'masks', 'drama'] },
    { emoji: '🎤', tags: ['microphone', 'sing', 'karaoke'] },
    { emoji: '🎧', tags: ['headphones', 'music', 'listen'] },
    { emoji: '🎼', tags: ['musical score'] },
    { emoji: '🎹', tags: ['piano', 'keyboard'] },
    { emoji: '🥁', tags: ['drum'] },
    { emoji: '🎷', tags: ['saxophone', 'jazz'] },
    { emoji: '🎺', tags: ['trumpet'] },
    { emoji: '🎸', tags: ['guitar', 'rock'] },
    { emoji: '🪕', tags: ['banjo'] },
    { emoji: '🎻', tags: ['violin'] },
    { emoji: '🎬', tags: ['movie', 'clapperboard', 'cinema'] },
    { emoji: '🏆', tags: ['trophy', 'winner', 'first place'] },
    { emoji: '🥇', tags: ['gold medal', 'first'] },
    { emoji: '🥈', tags: ['silver medal', 'second'] },
    { emoji: '🥉', tags: ['bronze medal', 'third'] }
  ],
  travel: [
    { emoji: '🚗', tags: ['car', 'automobile'] },
    { emoji: '🚕', tags: ['taxi', 'cab'] },
    { emoji: '🚙', tags: ['suv', 'recreational'] },
    { emoji: '🚌', tags: ['bus'] },
    { emoji: '🚎', tags: ['trolleybus'] },
    { emoji: '🏎️', tags: ['race car', 'f1', 'fast'] },
    { emoji: '🚓', tags: ['police car'] },
    { emoji: '🚑', tags: ['ambulance'] },
    { emoji: '🚒', tags: ['fire engine'] },
    { emoji: '🚐', tags: ['minibus'] },
    { emoji: '🛻', tags: ['pickup truck'] },
    { emoji: '🚚', tags: ['delivery truck'] },
    { emoji: '🚛', tags: ['articulated lorry'] },
    { emoji: '🚜', tags: ['tractor'] },
    { emoji: '🦯', tags: ['white cane'] },
    { emoji: '🦽', tags: ['manual wheelchair'] },
    { emoji: '🦼', tags: ['motorized wheelchair'] },
    { emoji: '🛴', tags: ['scooter'] },
    { emoji: '🚲', tags: ['bicycle', 'bike'] },
    { emoji: '🛵', tags: ['motor scooter'] },
    { emoji: '🏍️', tags: ['motorcycle', 'speed'] },
    { emoji: '🚨', tags: ['siren', 'emergency', 'alert', 'police'] },
    { emoji: '🚔', tags: ['oncoming police car'] },
    { emoji: '🚍', tags: ['oncoming bus'] },
    { emoji: '🚘', tags: ['oncoming automobile'] },
    { emoji: '🚖', tags: ['oncoming taxi'] },
    { emoji: '🚡', tags: ['aerial tramway'] },
    { emoji: '🚠', tags: ['mountain cableway'] },
    { emoji: '🚟', tags: ['suspension railway'] },
    { emoji: '🚃', tags: ['railway car'] },
    { emoji: '🚋', tags: ['tram car'] },
    { emoji: '🚞', tags: ['mountain railway'] },
    { emoji: '🚝', tags: ['monorail'] },
    { emoji: '🚄', tags: ['high speed train', 'bullet train'] },
    { emoji: '🚅', tags: ['bullet train nose'] },
    { emoji: '🚈', tags: ['light rail'] },
    { emoji: '🚂', tags: ['locomotive', 'train'] },
    { emoji: '🚆', tags: ['train'] },
    { emoji: '🚇', tags: ['metro', 'subway'] },
    { emoji: '🚊', tags: ['tram'] },
    { emoji: '🚉', tags: ['station'] },
    { emoji: '✈️', tags: ['airplane', 'flight', 'travel'] },
    { emoji: '🛫', tags: ['airplane departure'] },
    { emoji: '🛬', tags: ['airplane arrival'] },
    { emoji: '🛩️', tags: ['small airplane'] },
    { emoji: '💺', tags: ['seat', 'chair'] },
    { emoji: '🛰️', tags: ['satellite', 'space', 'orbit', 'relay'] },
    { emoji: '🚀', tags: ['rocket', 'space', 'launch', 'moon'] },
    { emoji: '🛸', tags: ['flying saucer', 'ufo'] },
    { emoji: '🚁', tags: ['helicopter'] },
    { emoji: '🛶', tags: ['canoe'] },
    { emoji: '⛵', tags: ['sailboat'] },
    { emoji: '🚤', tags: ['speedboat'] },
    { emoji: '🛥️', tags: ['motor boat'] },
    { emoji: '🛳️', tags: ['passenger ship'] },
    { emoji: '⛴️', tags: ['ferry'] },
    { emoji: '🚢', tags: ['ship'] },
    { emoji: '⚓', tags: ['anchor', 'port'] },
    { emoji: '⛽', tags: ['fuel pump', 'gas'] },
    { emoji: '🚧', tags: ['construction', 'barrier'] },
    { emoji: '🚦', tags: ['traffic light'] },
    { emoji: '🚥', tags: ['horizontal traffic light'] },
    { emoji: '🗺️', tags: ['world map', 'navigation'] },
    { emoji: '🗿', tags: ['moai', 'statue', 'stone'] },
    { emoji: '🗽', tags: ['statue of liberty'] },
    { emoji: '🗼', tags: ['tokyo tower'] },
    { emoji: '🏰', tags: ['castle'] },
    { emoji: '🏯', tags: ['japanese castle'] },
    { emoji: '🏟️', tags: ['stadium'] },
    { emoji: '🎡', tags: ['ferris wheel'] },
    { emoji: '🎢', tags: ['roller coaster'] },
    { emoji: '🎠', tags: ['carousel horse'] },
    { emoji: '⛲', tags: ['fountain'] },
    { emoji: '⛱️', tags: ['umbrella on ground'] },
    { emoji: '🏖️', tags: ['beach with umbrella'] },
    { emoji: '🏝️', tags: ['desert island'] },
    { emoji: '🏜️', tags: ['desert'] },
    { emoji: '🌋', tags: ['volcano', 'eruption'] },
    { emoji: '⛰️', tags: ['mountain'] },
    { emoji: '🏔️', tags: ['snow capped mountain'] },
    { emoji: '🏕️', tags: ['camping', 'tent'] }
  ],
  objects: [
    { emoji: '💡', tags: ['light bulb', 'idea', 'innovation'] },
    { emoji: '🔦', tags: ['flashlight'] },
    { emoji: '🏮', tags: ['red paper lantern'] },
    { emoji: '🪔', tags: ['diya lamp'] },
    { emoji: '🧱', tags: ['brick', 'firewall'] },
    { emoji: '🪵', tags: ['wood'] },
    { emoji: '📱', tags: ['mobile phone', 'smartphone', 'cell'] },
    { emoji: '📲', tags: ['calling phone'] },
    { emoji: '☎️', tags: ['telephone'] },
    { emoji: '📞', tags: ['telephone receiver'] },
    { emoji: '📟', tags: ['pager', 'retro'] },
    { emoji: '📠', tags: ['fax machine'] },
    { emoji: '🔋', tags: ['battery', 'power'] },
    { emoji: '🪫', tags: ['low battery'] },
    { emoji: '🔌', tags: ['electric plug'] },
    { emoji: '💻', tags: ['laptop', 'computer', 'pc'] },
    { emoji: '🖥️', tags: ['desktop computer'] },
    { emoji: '🖨️', tags: ['printer'] },
    { emoji: '⌨️', tags: ['keyboard'] },
    { emoji: '🖱️', tags: ['computer mouse'] },
    { emoji: '💾', tags: ['floppy disk', 'save'] },
    { emoji: '💿', tags: ['optical disk', 'cd'] },
    { emoji: '📀', tags: ['dvd'] },
    { emoji: '🧮', tags: ['abacus'] },
    { emoji: '🎥', tags: ['movie camera'] },
    { emoji: '🎞️', tags: ['film frames'] },
    { emoji: '📽️', tags: ['film projector'] },
    { emoji: '📺', tags: ['television', 'tv'] },
    { emoji: '📷', tags: ['camera', 'photo'] },
    { emoji: '📸', tags: ['camera with flash'] },
    { emoji: '📹', tags: ['video camera'] },
    { emoji: '📼', tags: ['videocassette', 'vhs'] },
    { emoji: '🔍', tags: ['magnifying glass left', 'search'] },
    { emoji: '🔎', tags: ['magnifying glass right', 'find'] },
    { emoji: '🕯️', tags: ['candle'] },
    { emoji: '🪙', tags: ['coin', 'crypto', 'bitcoin'] },
    { emoji: '💵', tags: ['dollar banknote', 'money'] },
    { emoji: '💴', tags: ['yen banknote'] },
    { emoji: '💶', tags: ['euro banknote'] },
    { emoji: '💷', tags: ['pound banknote'] },
    { emoji: '💳', tags: ['credit card', 'payment'] },
    { emoji: '💎', tags: ['gem stone', 'diamond', 'rich'] },
    { emoji: '⚖️', tags: ['balance scale', 'law', 'justice'] },
    { emoji: '🪜', tags: ['ladder'] },
    { emoji: '🧰', tags: ['toolbox'] },
    { emoji: '🪛', tags: ['screwdriver'] },
    { emoji: '🔧', tags: ['wrench', 'tool', 'settings'] },
    { emoji: '🔨', tags: ['hammer'] },
    { emoji: '⚒️', tags: ['hammer and pick'] },
    { emoji: '🛠️', tags: ['hammer and wrench'] },
    { emoji: '⛏️', tags: ['pick'] },
    { emoji: '🪚', tags: ['carpentry saw'] },
    { emoji: '🔩', tags: ['nut and bolt'] },
    { emoji: '⚙️', tags: ['gear', 'settings', 'config'] },
    { emoji: '🪤', tags: ['mouse trap'] },
    { emoji: '🧲', tags: ['magnet'] },
    { emoji: '🔫', tags: ['water pistol', 'gun'] },
    { emoji: '💣', tags: ['bomb', 'explosion'] },
    { emoji: '🧨', tags: ['firecracker'] },
    { emoji: '🗡️', tags: ['dagger', 'knife'] },
    { emoji: '⚔️', tags: ['crossed swords'] },
    { emoji: '🛡️', tags: ['shield', 'security', 'defense', 'protect'] },
    { emoji: '🔑', tags: ['key', 'password', 'crypto', 'lock'] },
    { emoji: '🗝️', tags: ['old key'] },
    { emoji: '🔒', tags: ['locked', 'secure', 'encrypted', 'safe'] },
    { emoji: '🔓', tags: ['unlocked', 'open'] },
    { emoji: '🔏', tags: ['locked with pen'] },
    { emoji: '🔐', tags: ['locked with key'] },
    { emoji: '📡', tags: ['satellite antenna', 'dish', 'transmission', 'signal'] },
    { emoji: '🔭', tags: ['telescope'] },
    { emoji: '🔬', tags: ['microscope'] },
    { emoji: '💊', tags: ['pill', 'medicine'] },
    { emoji: '💉', tags: ['syringe', 'vaccine'] },
    { emoji: '🧬', tags: ['dna', 'genetics'] },
    { emoji: '🧪', tags: ['test tube', 'science'] },
    { emoji: '🧫', tags: ['petri dish'] },
    { emoji: '🧯', tags: ['fire extinguisher'] },
    { emoji: '🛒', tags: ['shopping cart'] }
  ],
  symbols: [
    { emoji: '❤️', tags: ['red heart', 'love'] },
    { emoji: '🧡', tags: ['orange heart'] },
    { emoji: '💛', tags: ['yellow heart'] },
    { emoji: '💚', tags: ['green heart'] },
    { emoji: '💙', tags: ['blue heart'] },
    { emoji: '💜', tags: ['purple heart'] },
    { emoji: '🖤', tags: ['black heart'] },
    { emoji: '🤍', tags: ['white heart'] },
    { emoji: '🤎', tags: ['brown heart'] },
    { emoji: '💔', tags: ['broken heart'] },
    { emoji: '❣️', tags: ['heart exclamation'] },
    { emoji: '💕', tags: ['two hearts'] },
    { emoji: '💞', tags: ['revolving hearts'] },
    { emoji: '💓', tags: ['beating heart'] },
    { emoji: '💗', tags: ['growing heart'] },
    { emoji: '💖', tags: ['sparkling heart'] },
    { emoji: '💘', tags: ['heart with arrow'] },
    { emoji: '💝', tags: ['heart with ribbon'] },
    { emoji: '💟', tags: ['heart decoration'] },
    { emoji: '☮️', tags: ['peace symbol'] },
    { emoji: '☯️', tags: ['yin yang'] },
    { emoji: '🆔', tags: ['id button', 'identity'] },
    { emoji: '⚛️', tags: ['atom symbol', 'physics', 'quantum'] },
    { emoji: '☣️', tags: ['biohazard', 'danger'] },
    { emoji: '☢️', tags: ['radioactive', 'nuclear'] },
    { emoji: '📳', tags: ['vibration mode'] },
    { emoji: '🆘', tags: ['sos button', 'help'] },
    { emoji: '❌', tags: ['cross mark', 'x', 'cancel'] },
    { emoji: '⭕', tags: ['hollow red circle'] },
    { emoji: '🛑', tags: ['stop sign'] },
    { emoji: '⛔', tags: ['no entry'] },
    { emoji: '🚫', tags: ['prohibited', 'no'] },
    { emoji: '💯', tags: ['hundred points', 'perfect', '100'] },
    { emoji: '⚠️', tags: ['warning', 'danger', 'hazard'] },
    { emoji: '♻️', tags: ['recycling symbol'] },
    { emoji: '✅', tags: ['check mark button', 'verified', 'done'] },
    { emoji: '🌐', tags: ['globe with meridians', 'internet', 'network'] },
    { emoji: '📶', tags: ['antenna bars', 'signal', 'wifi'] },
    { emoji: '🔣', tags: ['input symbols'] },
    { emoji: 'ℹ️', tags: ['information'] },
    { emoji: '🆗', tags: ['ok button'] },
    { emoji: '🆕', tags: ['new button'] },
    { emoji: '🆓', tags: ['free button'] },
    { emoji: '▶️', tags: ['play button'] },
    { emoji: '⏸️', tags: ['pause button'] },
    { emoji: '⏹️', tags: ['stop button'] },
    { emoji: '🔁', tags: ['repeat button'] },
    { emoji: '🔄', tags: ['counterclockwise arrows', 'sync'] },
    { emoji: '⚡', tags: ['high voltage', 'lightning', 'zap', 'power', 'fast'] },
    { emoji: '🔥', tags: ['fire', 'flame', 'hot', 'lit'] },
    { emoji: '✨', tags: ['sparkles', 'magic', 'clean', 'star'] },
    { emoji: '⭐', tags: ['star', 'favorite'] },
    { emoji: '🌟', tags: ['glowing star'] },
    { emoji: '💥', tags: ['collision', 'boom', 'bang'] }
  ],
  flags: [
    { emoji: '🏁', tags: ['chequered flag', 'race'] },
    { emoji: '🚩', tags: ['red flag', 'warning'] },
    { emoji: '🏴‍☠️', tags: ['pirate flag'] },
    { emoji: '🇺🇸', tags: ['united states', 'usa', 'america'] },
    { emoji: '🇬🇧', tags: ['united kingdom', 'uk', 'britain'] },
    { emoji: '🇨🇦', tags: ['canada'] },
    { emoji: '🇦🇺', tags: ['australia'] },
    { emoji: '🇮🇳', tags: ['india'] },
    { emoji: '🇩🇪', tags: ['germany'] },
    { emoji: '🇫🇷', tags: ['france'] },
    { emoji: '🇯🇵', tags: ['japan'] },
    { emoji: '🇰🇷', tags: ['south korea'] },
    { emoji: '🇨🇳', tags: ['china'] },
    { emoji: '🇧🇷', tags: ['brazil'] },
    { emoji: '🇷🇺', tags: ['russia'] },
    { emoji: '🇮🇹', tags: ['italy'] },
    { emoji: '🇪🇸', tags: ['spain'] },
    { emoji: '🇲🇽', tags: ['mexico'] },
    { emoji: '🇿🇦', tags: ['south africa'] },
    { emoji: '🇳🇬', tags: ['nigeria'] },
    { emoji: '🇦🇪', tags: ['united arab emirates', 'uae', 'dubai'] },
    { emoji: '🇸🇦', tags: ['saudi arabia'] },
    { emoji: '🇨🇭', tags: ['switzerland'] },
    { emoji: '🇸🇪', tags: ['sweden'] },
    { emoji: '🇳🇱', tags: ['netherlands'] },
    { emoji: '🇸🇬', tags: ['singapore'] }
  ]
};

// Curated Cyberpunk animated badge stickers
export const CYBER_STICKERS = [
  {
    id: 'access_granted',
    title: 'ACCESS GRANTED',
    badge: '🔓 ACCESS: GRANTED',
    color: '#00F0FF',
    sub: 'SECURITY CLEARANCE: LVL-5',
    icon: '⚡'
  },
  {
    id: 'quantum_shield',
    title: 'QUANTUM SHIELD',
    badge: '🛡️ QUANTUM: ACTIVE',
    color: '#00F0FF',
    sub: 'ML-KEM-768 LATTICE ENGAGED',
    icon: '🛡️'
  },
  {
    id: 'system_override',
    title: 'SYSTEM OVERRIDE',
    badge: '⚠️ SYSTEM: OVERRIDE',
    color: '#FFB800',
    sub: 'ROOT PRIVILEGES SEIZED',
    icon: '🔥'
  },
  {
    id: 'top_secret',
    title: 'TOP SECRET',
    badge: '🔒 CLASSIFIED: TOP SECRET',
    color: '#FF0055',
    sub: 'EYES ONLY // FORWARD SECRECY',
    icon: '👁️'
  },
  {
    id: 'stealth_active',
    title: 'STEALTH MODE',
    badge: '👻 PROTOCOL: STEALTH',
    color: '#94A3B8',
    sub: 'SEALED SENDER METADATA ZEROED',
    icon: '🕶️'
  },
  {
    id: 'hacker_cat',
    title: 'CYBER FELINE',
    badge: '🐱 ROOT@KITTEN:~#',
    color: '#00F0FF',
    sub: 'MAINFRAME BYPASSED VIA NAPS',
    icon: '🐱'
  },
  {
    id: 'mission_complete',
    title: 'MISSION SUCCESS',
    badge: '🎯 MISSION: COMPLETED',
    color: '#10B981',
    sub: 'CIPHERTEXT DELIVERED 100%',
    icon: '✅'
  },
  {
    id: 'breach_deflected',
    title: 'BREACH DEFLECTED',
    badge: '🚫 HACK ATTEMPT DEFLECTED',
    color: '#FF0055',
    sub: 'POST-QUANTUM RATCHET RE-KEYED',
    icon: '💥'
  }
];

// Curated GIF categories with fast reliable previews
export const GIF_PRESETS = [
  {
    category: 'Trending',
    gifs: [
      { id: 'g1', title: 'Hacker typing', url: 'https://media.giphy.com/media/YQitE4YNQNahy/giphy.gif', preview: 'https://media.giphy.com/media/YQitE4YNQNahy/200w.gif' },
      { id: 'g2', title: 'Cyberpunk City', url: 'https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif', preview: 'https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/200w.gif' },
      { id: 'g3', title: 'Mind Blown', url: 'https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif', preview: 'https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/200w.gif' },
      { id: 'g4', title: 'Applause', url: 'https://media.giphy.com/media/nbvFVPiEiJH6Q/giphy.gif', preview: 'https://media.giphy.com/media/nbvFVPiEiJH6Q/200w.gif' },
      { id: 'g5', title: 'Laughing Cat', url: 'https://media.giphy.com/media/BzyTuYCmvSORqs1ABM/giphy.gif', preview: 'https://media.giphy.com/media/BzyTuYCmvSORqs1ABM/200w.gif' },
      { id: 'g6', title: 'Yes / Agree', url: 'https://media.giphy.com/media/10Jpr9KSaXLchW/giphy.gif', preview: 'https://media.giphy.com/media/10Jpr9KSaXLchW/200w.gif' }
    ]
  },
  {
    category: 'Cyber / Hacker',
    gifs: [
      { id: 'c1', title: 'Matrix Code Rain', url: 'https://media.giphy.com/media/eIm624uf8hnxm/giphy.gif', preview: 'https://media.giphy.com/media/eIm624uf8hnxm/200w.gif' },
      { id: 'c2', title: 'I am in', url: 'https://media.giphy.com/media/YQitE4YNQNahy/giphy.gif', preview: 'https://media.giphy.com/media/YQitE4YNQNahy/200w.gif' },
      { id: 'c3', title: 'Cyberpunk Glitch', url: 'https://media.giphy.com/media/l41lFw057lAJQMwg0/giphy.gif', preview: 'https://media.giphy.com/media/l41lFw057lAJQMwg0/200w.gif' },
      { id: 'c4', title: 'Security Access', url: 'https://media.giphy.com/media/ule4akeXnY9A50FYME/giphy.gif', preview: 'https://media.giphy.com/media/ule4akeXnY9A50FYME/200w.gif' }
    ]
  },
  {
    category: 'Reaction / Humor',
    gifs: [
      { id: 'r1', title: 'Shocked', url: 'https://media.giphy.com/media/5VKbvrjxpVJCM/giphy.gif', preview: 'https://media.giphy.com/media/5VKbvrjxpVJCM/200w.gif' },
      { id: 'r2', title: 'Popcorn', url: 'https://media.giphy.com/media/t3dLl0TGHCxTG/giphy.gif', preview: 'https://media.giphy.com/media/t3dLl0TGHCxTG/200w.gif' },
      { id: 'r3', title: 'Facepalm', url: 'https://media.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif', preview: 'https://media.giphy.com/media/TJawtKM6OCKkvwCIqX/200w.gif' },
      { id: 'r4', title: 'Dance celebration', url: 'https://media.giphy.com/media/blSTtZehjAZ8I/giphy.gif', preview: 'https://media.giphy.com/media/blSTtZehjAZ8I/200w.gif' }
    ]
  }
];
